services:
  valhalla:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    container_name: urban-access-valhalla
    ports:
      - "8002:8002"
    volumes:
      - ./valhalla_data:/custom_files
    environment:
      # Estratto OSM del Trentino-Alto Adige da Geofabrik
      - tile_urls=https://download.geofabrik.de/europe/italy/nord-est-latest.osm.pbf
      - serve_tiles=True
      - build_elevation=False
      - build_admins=True
      - build_time_zones=False
      - use_default_speeds_config=True
      - server_threads=2